# Generated by Django 3.2.7 on 2021-10-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211022_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='produto',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(related_name='produtos', to='home.Categoria'),
        ),
    ]
