# Generated by Django 3.2.7 on 2021-10-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211022_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(related_name='produto', to='home.Categoria'),
        ),
    ]
