# Generated by Django 3.2.7 on 2021-10-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_produto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='is_available',
            new_name='is_avaliable',
        ),
    ]
